DTSPO-14559 - Allow excluding external-dns
hmcts/chart-library pull request #111
Opened 2023-11-09 15:32 UTC by endakelly

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-14559

### Change description ###
Add value that consuming charts can set to allow disabling of external-dns on certain ingresses where required
External-dns will be enabled by default

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2023-11-09 16:05 UTC, timja requested changes

2023-11-09 16:05 UTC, timja commented on library/templates/v2/_ingress.tpl
> +    external-dns.alpha.kubernetes.io/exclude: "true"
maybe better to just allow arbitrary annotations to be added?

2023-11-09 16:05 UTC, timja commented on library/tests/snapshot-tests/__snapshot__/ingress_test.yaml.snap
> +        external-dns.alpha.kubernetes.io/exclude: "true"
this shouldn't be the default, add a separate unit test for it

2023-11-09 16:38 UTC, endakelly commented on library/tests/snapshot-tests/__snapshot__/ingress_test.yaml.snap
> +        external-dns.alpha.kubernetes.io/exclude: "true"
Might be redundant with the updates I've made to just add any desired annotations but getting an error when running helm unittest: `template "library/templates/v2/configmap.yaml" not exists or not selected in test suite`

I'm not well up on how these tests work, what's this error really mean?

2023-11-09 16:50 UTC, timja commented on library/tests/snapshot-tests/__snapshot__/ingress_test.yaml.snap
> +        external-dns.alpha.kubernetes.io/exclude: "true"
not sure maybe ping Daniel C if you need a hand, (they worked for me fine last time I tried though)

2023-11-10 09:07 UTC, endakelly commented on library/tests/snapshot-tests/__snapshot__/ingress_test.yaml.snap
> +        external-dns.alpha.kubernetes.io/exclude: "true"
Passing again now. The helm unittest command listed in the readme errors but it's erroring on multiple files not related to this and the pipeline is passing

2023-11-10 11:15 UTC, timja requested changes
please add a unittest for this

2023-11-10 12:10 UTC, timja commented on library/tests/unit-tests/ingress_test.yaml
> +          path: metadata.annotations
can you assert the actual annotations please and not just not null?

2023-11-10 12:39 UTC, timja approved these changes

2023-11-10 12:41 UTC, merged