DTSPO-6533 Update chart library to use ingressClassName
hmcts/chart-library pull request #48
Opened 2022-02-02 13:31 UTC by zc-hmcts

### JIRA link ###
https://tools.hmcts.net/jira/browse/DTSPO-6533

### Change description ###
DTSPO-6533 Update chart library to use ingressClassName  instead of annotation which is deprecated, as per https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#what-to-do

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-02-02 13:37 UTC, timja commented on library/templates/v2/_ingress.tpl
> -    kubernetes.io/ingress.class: {{ $languageValues.ingressClass }}
need to be kept by default, with a flag enable it as traefik v1  doesn't support the non deprecated version unfortunately and CFT haven't upgraded yet. (search feature flag in the story, sorry if it wasn't clear enough)

2022-02-02 13:38 UTC, timja commented on library/templates/v2/_ingress.tpl
> +  ingressClassName: {{ $languageValues.ingressClassName }}
this should be fine to always be here thinking about it, if traefik v1 doesn't support it it should just be ignored

2022-02-02 18:42 UTC, timja commented on library/templates/v2/_ingress.tpl
> +    {{- if not .spec.ingressClassName }}
prob something like this instead:
```suggestion
    {{- if not .spec.disableIngressClassAnnotation }}
```

2022-02-02 18:42 UTC, timja commented on library/templates/v2/_ingress.tpl
> +  ingressClassName: {{ $languageValues.ingressClassName }}
we don't want to break people already setting it i think
```suggestion
  ingressClassName: {{ $languageValues.ingressClass }}
```

2022-02-02 18:47 UTC, timja commented on ci-values.yaml
> +  enabled: true
did you mean to change this?

2022-02-02 18:48 UTC, timja commented on library/templates/v2/_ingress.tpl
> +        PathType: Prefix
tests will prob need updating for this

2022-02-02 19:57 UTC, timja commented on library/templates/v2/_ingress.tpl
> +      service:
missing pathType in this part of the test

2022-02-02 19:58 UTC, timja commented on tests/results/ingress.yaml
> +  ingressClassName: traefik
missing pathType in test below

2022-02-03 10:25 UTC, timja approved these changes
LGTM

2022-02-03 12:04 UTC, timja commented on ci-values.yaml
> +spec: {}
what's this?

2022-02-03 12:04 UTC, timja commented on library/templates/v2/_hpa.tpl
> +{{- if $languageValues.autoscaling }}
should probably have an and .enabled as well, i think it was assuming this was always present is it now?

2022-02-03 12:04 UTC, timja commented on library/templates/v2/_ingress.tpl
> +{{ if or ($languageValues.ingressHost ) ($languageValues.registerAdditionalDns) }}
needs to still check enabled

2022-02-03 12:26 UTC, zc-hmcts commented on ci-values.yaml
> +spec: {}
without it I get this error `nil pointer evaluating interface {}.disableIngressClassAnnotation` https://github.com/helm/helm/issues/8026

2022-02-03 13:15 UTC, timja requested changes

2022-02-03 13:15 UTC, timja commented on ci-values-lang.yaml
> +spec:
this should be at the top level not spec

2022-02-03 13:15 UTC, timja commented on library/templates/v2/_ingress.tpl
> +    {{- if not $languageValues.spec.disableIngressClassAnnotation }}
this will fix the issue
```suggestion
    {{- if not $languageValues.disableIngressClassAnnotation }}
```

2022-02-03 13:15 UTC, timja commented on library/templates/v2/_ingress.tpl
>  {{- end -}}
on line 1 the version needs incrementing to v3, also needs updating in consumers search the repo

2022-02-03 13:15 UTC, timja commented on ci-values.yaml
> +spec: {}
I added a suggestion for fixing that

2022-02-03 13:43 UTC, timja commented on library/templates/v2/_ingress.tpl
> -  - host: {{ $languageValues.registerAdditionalDns.prefix }}-{{ tpl $languageValues.registerAdditionalDns.primaryIngressHost $ }}
these changes need reverting

2022-02-03 15:36 UTC, timja approved these changes

2022-02-03 15:37 UTC, merged