VIH-9293 - Add custom mount path for key vaults
hmcts/chart-library pull request #65
Opened 2022-09-07 07:54 UTC by chris-pateman

### JIRA link (if applicable) ###
VIH-9293

### Change description ###
Add custom mount path for the key vaults.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-09-07 12:51 UTC, timja requested changes
I'm not 100% sure we want this, as still our recommendation is to adapt the application.

The current minor style issues with the PR are below

2022-09-07 12:51 UTC, timja commented on library/Chart.yaml
> +
revert all these extra blank lines generally it's making it harder to read

2022-09-07 12:51 UTC, timja commented on library/templates/v2/_deployment_test_helpers.tpl
> +    volumeMounts:
```suggestion
    volumeMounts:
```

2022-09-07 12:51 UTC, timja commented on library/templates/v2/_secretcsivolumes.tpl
> +Mount the Key vaults on /mnt/secrets by Default or the custom path
```suggestion
Mount the Key vaults on /mnt/secrets by default or the custom mountPath
```

2022-09-07 12:51 UTC, timja commented on tests/results/secretproviderclass.yaml
> +    tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
```suggestion
    tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"

```

2022-09-07 13:02 UTC, chris-pateman commented on tests/results/secretproviderclass.yaml
> +    tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
Corrected

2022-09-07 13:02 UTC, chris-pateman commented on library/templates/v2/_secretcsivolumes.tpl
> +Mount the Key vaults on /mnt/secrets by Default or the custom path
Corrected

2022-09-07 13:02 UTC, chris-pateman commented on library/templates/v2/_deployment_test_helpers.tpl
> +    volumeMounts:
Corrected

2022-09-07 13:02 UTC, chris-pateman commented on library/Chart.yaml
> +
Corrected

2022-09-13 15:38 UTC, timja approved these changes

2022-09-14 12:47 UTC, merged